
# window

WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 832
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

BATTLE_WINDOW_WIDTH = 1700
BATTLE_WINDOW_HEIGHT = 950
BATTLE_WINDOW_SIZE = (BATTLE_WINDOW_WIDTH, BATTLE_WINDOW_HEIGHT)


# color

WHITE = (255, 255, 255)
GRAY = (150, 150, 150)
BLACK = (0, 0, 0)
BROWN = (69, 30, 0)
RED = (135, 25, 16)
GREEN = (25, 110, 20)

# font
FONT_FILE = "./srcs/NikkyouSans.ttf"
FONT_SIZE = 40
SUB_FONT_SIZE = 30

# yubi_key
YUBI_KEY_TITLE = "Yubi Key"


# sashimida

TITLE = "sashimida"
RAIL_SPEED = 2
BATTLE_RAIL_SPEED = 4
PLAY_TIME = 120
QUESTIONS_FILE = "./srcs/questions.txt"

BGM_FLAG = True

HEADER_FONT_FILE = "./srcs/Shokakiutage.ttf"
HEADER_FONT_SIZE = 80
TYPED_COLOR = (238, 120, 0)
REMAINING_COLOR = (255, 255, 255)


# title

TITLE_BUTTON_FONT_FILE = "./srcs/Aiharaedomoji.ttf"
TITLE_BUTTON_FONT_SIZE = 40
SASHIMI_MARGIN = 350
TITLE_RAIL_SPEED = 1

